// constants/products.dart
final List<Map<String, dynamic>> products = [
  {
    'product_id': 1,
    'prod_line_id': 101,
    'artist_id': 501,
    'prod_name': 'The Sunflower',
    'prod_description': 'A beautiful sunflower painting',
    'prod_dimensions': '40x50 cm',
    'prod_medium': 'Watercolor',
    'prod_image': 'sunflower.jpg',
    'prod_price': 1500.0,
    'prod_stock_quantity': 10,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 2,
  },
  {
    'product_id': 2,
    'prod_line_id': 102,
    'artist_id': 502,
    'prod_name': 'The Rose',
    'prod_description': 'A delicate rose oil painting',
    'prod_dimensions': '30x40 cm',
    'prod_medium': 'Oil Painting',
    'prod_image': 'rose.jpg',
    'prod_price': 1200.0,
    'prod_stock_quantity': 5,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 1,
  },
  {
    'product_id': 3,
    'prod_line_id': 103,
    'artist_id': 503,
    'prod_name': 'The Tulip',
    'prod_description': 'A vibrant tulip acrylic artwork',
    'prod_dimensions': '35x45 cm',
    'prod_medium': 'Acrylic',
    'prod_image': 'tulip.jpg',
    'prod_price': 1300.0,
    'prod_stock_quantity': 8,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 3,
  },
  {
    'product_id': 4,
    'prod_line_id': 104,
    'artist_id': 504,
    'prod_name': 'The Daisy',
    'prod_description': 'A simple yet elegant daisy drawing',
    'prod_dimensions': '25x35 cm',
    'prod_medium': 'Charcoal',
    'prod_image': 'daisy.jpg',
    'prod_price': 900.0,
    'prod_stock_quantity': 12,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 0,
  },
  {
    'product_id': 5,
    'prod_line_id': 105,
    'artist_id': 505,
    'prod_name': 'The Lily',
    'prod_description': 'A pastel masterpiece of a lily',
    'prod_dimensions': '28x38 cm',
    'prod_medium': 'Pastel',
    'prod_image': 'lily.jpg',
    'prod_price': 1100.0,
    'prod_stock_quantity': 7,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 4,
  },
  {
    'product_id': 6,
    'prod_line_id': 106,
    'artist_id': 506,
    'prod_name': 'The Orchid',
    'prod_description': 'A stunning orchid in vivid colors',
    'prod_dimensions': '32x42 cm',
    'prod_medium': 'Acrylic',
    'prod_image': 'orchid.jpg',
    'prod_price': 1400.0,
    'prod_stock_quantity': 6,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 2,
  },
  {
    'product_id': 7,
    'prod_line_id': 107,
    'artist_id': 507,
    'prod_name': 'The Poppy',
    'prod_description': 'A bold and bright poppy painting',
    'prod_dimensions': '30x40 cm',
    'prod_medium': 'Oil Painting',
    'prod_image': 'poppy.jpg',
    'prod_price': 1250.0,
    'prod_stock_quantity': 9,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 3,
  },
  {
    'product_id': 8,
    'prod_line_id': 108,
    'artist_id': 508,
    'prod_name': 'The Peony',
    'prod_description': 'A luxurious and soft peony artwork',
    'prod_dimensions': '45x55 cm',
    'prod_medium': 'Watercolor',
    'prod_image': 'peony.jpg',
    'prod_price': 1600.0,
    'prod_stock_quantity': 4,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 5,
  },
  {
    'product_id': 9,
    'prod_line_id': 109,
    'artist_id': 509,
    'prod_name': 'The Magnolia',
    'prod_description': 'A peaceful and elegant magnolia sketch',
    'prod_dimensions': '27x37 cm',
    'prod_medium': 'Pencil Sketch',
    'prod_image': 'magnolia.jpg',
    'prod_price': 950.0,
    'prod_stock_quantity': 10,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 1,
  },
  {
    'product_id': 10,
    'prod_line_id': 110,
    'artist_id': 510,
    'prod_name': 'The Camellia',
    'prod_description': 'A dreamy pastel camellia piece',
    'prod_dimensions': '33x43 cm',
    'prod_medium': 'Pastel',
    'prod_image': 'camellia.jpg',
    'prod_price': 1150.0,
    'prod_stock_quantity': 7,
    'prod_date_added': DateTime.now(),
    'prod_status': 'available',
    'prod_sold': 2,
  },
];

final String pesoSign = '\u20B1';
